# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=200)),
                ('network_code', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('physical_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Primary_canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_canal_name', models.CharField(max_length=200)),
                ('primary_canal_code', models.CharField(max_length=100)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manyire.Network')),
            ],
        ),
    ]
