# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manyire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
