# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manyire', '0002_network_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary_canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_canal_name', models.CharField(max_length=200)),
                ('secondary_canal_code', models.CharField(max_length=100)),
                ('primary_canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manyire.Primary_canal')),
            ],
        ),
        migrations.CreateModel(
            name='Tertiary_canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tertiary_canal_name', models.CharField(max_length=200)),
                ('tertiary_canal_code', models.CharField(max_length=100)),
                ('secondary_canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manyire.Secondary_canal')),
            ],
        ),
    ]
